export const SET_FILTER = "SET_FILTER";
export const ADD_EVENT = "ADD_EVENT";
export const TOGGLE_EVENT = "TOGGLE_EVENT"
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';
